export const CATEGORIES = {
  rompighiaccio: { label: "Rompighiaccio", color: "#3FA396" },
  profondo: { label: "Profondo", color: "#8567C9" },
  divertente: { label: "Divertente", color: "#D6608F" },
  ricordi: { label: "Ricordi", color: "#7CAD6B" },
  sfida: { label: "Sfida", color: "#C24B4B" },
  intimita: { label: "Intimità", color: "#9C3B57", coupleOnly: true },
  quiz: { label: "Quiz", color: "#4A90D9", groupOnly: true },
};

export const CARDS = [
  { cat: "rompighiaccio", text: "Qual è l'ultima cosa che ti ha fatto ridere fino alle lacrime?" },
  { cat: "rompighiaccio", text: "Se potessi vivere in un'epoca diversa, quale sceglieresti e perché?" },
  { cat: "rompighiaccio", text: "Qual è il tuo modo preferito di iniziare la giornata?" },
  { cat: "rompighiaccio", text: "Descrivi la tua giornata perfetta, dall'alba al tramonto." },
  { cat: "rompighiaccio", text: "Qual è un'abitudine strana che hai e di cui vai fiero?" },
  { cat: "rompighiaccio", text: "Se il tuo umore di oggi fosse un tempo atmosferico, quale sarebbe?" },
  { cat: "rompighiaccio", text: "Qual è il piatto che cucineresti per stupire qualcuno?" },
  { cat: "rompighiaccio", text: "Che canzone ti fa venire subito voglia di ballare?" },
  { cat: "rompighiaccio", text: "Qual è il posto nel mondo che ti incuriosisce di più e non hai ancora visitato?" },
  { cat: "rompighiaccio", text: "Se potessi imparare una nuova lingua in un giorno, quale sceglieresti?" },
  { cat: "rompighiaccio", text: "Qual è l'ultimo libro, film o serie che ti ha sorpreso davvero?" },
  { cat: "rompighiaccio", text: "Che superpotere useresti solo per piccole comodità quotidiane?" },

  { cat: "profondo", text: "Qual è una paura che porti da tempo e non hai mai raccontato a nessuno?" },
  { cat: "profondo", text: "Cosa ti fa sentire davvero visto o vista dagli altri?" },
  { cat: "profondo", text: "Qual è il momento in cui ti sei sentito più orgoglioso di te stesso?" },
  { cat: "profondo", text: "Cosa vorresti che le persone capissero di te senza doverlo spiegare?" },
  { cat: "profondo", text: "Qual è una convinzione che avevi da giovane e che oggi non hai più?" },
  { cat: "profondo", text: "Cosa significa per te \"sentirsi a casa\" con qualcuno?" },
  { cat: "profondo", text: "Qual è il rimpianto più grande che porti con leggerezza, non con dolore?" },
  { cat: "profondo", text: "Cosa ti dà davvero coraggio nei momenti difficili?" },
  { cat: "profondo", text: "Qual è una cosa che ti aspetti da chi ti sta accanto e non hai mai chiesto ad alta voce?" },
  { cat: "profondo", text: "Se potessi guarire una ferita del passato con una sola parola, quale sarebbe?" },
  { cat: "profondo", text: "Cosa ti fa sentire libero o libera?" },
  { cat: "profondo", text: "Qual è il valore che non sei mai disposto a negoziare?" },

  { cat: "divertente", text: "Imita il modo in cui qualcuno del gruppo si sveglia al mattino." },
  { cat: "divertente", text: "Qual è la teoria più assurda in cui hai mai creduto anche solo per un momento?" },
  { cat: "divertente", text: "Se dovessi avere un soprannome scelto dagli altri qui presenti, quale ti aspetteresti?" },
  { cat: "divertente", text: "Racconta il selfie più imbarazzante che tu abbia mai scattato, anche solo a parole." },
  { cat: "divertente", text: "Qual è il cibo più strano che hai mai mangiato per curiosità?" },
  { cat: "divertente", text: "Inventa un balletto di 10 secondi e mostralo, o descrivilo a parole." },
  { cat: "divertente", text: "Se fossi un elettrodomestico, quale saresti e perché?" },
  { cat: "divertente", text: "Qual è la bugia più innocente che hai mai detto per evitare un imbarazzo?" },
  { cat: "divertente", text: "Racconta la volta in cui hai riso nel momento più sbagliato." },
  { cat: "divertente", text: "Se dovessi vendere online un tuo difetto, come lo descriveresti nell'annuncio?" },
  { cat: "divertente", text: "Qual è la canzone che canti sempre sbagliando le parole?" },
  { cat: "divertente", text: "Descrivi il tuo animale spirito immaginario in tre parole assurde." },

  { cat: "ricordi", text: "Qual è il ricordo d'infanzia che ti fa sorridere ogni volta che ci ripensi?" },
  { cat: "ricordi", text: "Racconta un viaggio che ha cambiato il modo in cui vedi le cose." },
  { cat: "ricordi", text: "Qual è la prima cosa che ricordi di aver desiderato con tutto il cuore da bambino?" },
  { cat: "ricordi", text: "Descrivi una persona che ha lasciato un segno nella tua vita, anche se l'hai incontrata poco." },
  { cat: "ricordi", text: "Qual è l'odore o il suono che ti riporta subito a un ricordo preciso?" },
  { cat: "ricordi", text: "Racconta il regalo più inaspettato che tu abbia mai ricevuto." },
  { cat: "ricordi", text: "Qual è la tradizione di famiglia a cui sei più legato?" },
  { cat: "ricordi", text: "Descrivi un momento in cui ti sei sentito completamente felice, senza motivo apparente." },
  { cat: "ricordi", text: "Qual è la lezione più importante che ti ha insegnato un errore del passato?" },
  { cat: "ricordi", text: "Racconta un'amicizia che ricordi con affetto anche se oggi non c'è più." },
  { cat: "ricordi", text: "Qual è il ricordo legato a una casa in cui hai vissuto che porti ancora con te?" },
  { cat: "ricordi", text: "Descrivi il momento in cui ti sei sentito più orgoglioso di qualcuno vicino a te." },

  { cat: "sfida", text: "Fai un complimento sincero e specifico alla persona alla tua destra." },
  { cat: "sfida", text: "Scambia un oggetto che hai con te con quello di un'altra persona per il resto del gioco." },
  { cat: "sfida", text: "Racconta agli altri una qualità di ciascuno di loro in una sola parola." },
  { cat: "sfida", text: "Chiudi gli occhi e descrivi a memoria il volto della persona che ti è più cara." },
  { cat: "sfida", text: "Fai una domanda scomoda a qualcuno: può scegliere se rispondere o pescare un'altra carta." },
  { cat: "sfida", text: "Proponi un brindisi improvvisato per il gruppo." },
  { cat: "sfida", text: "Racconta la storia dietro un'abitudine o un rito che fai sempre e nessuno conosce." },
  { cat: "sfida", text: "Cambia posto con qualcuno e guarda la scena da un altro punto di vista per un minuto." },
  { cat: "sfida", text: "Fai indovinare agli altri un tuo sogno nel cassetto usando solo i gesti." },
  { cat: "sfida", text: "Rivela una cosa che ammiri profondamente in una persona qui presente, guardandola negli occhi." },
  { cat: "sfida", text: "Racconta una decisione difficile che rifaresti uguale, senza rimpianti." },
  { cat: "sfida", text: "Lascia che qualcun altro scelga la prossima domanda per te, tra due categorie a sua scelta." },
  { cat: "rompighiaccio", text: "Qual è il tuo modo preferito di trascorrere una domenica senza impegni?" },
  { cat: "rompighiaccio", text: "Se potessi cambiare mestiere per un giorno, cosa faresti?" },
  { cat: "rompighiaccio", text: "Qual è l'oggetto a cui sei più affezionato e perché?" },
  { cat: "rompighiaccio", text: "Che tipo di musica ascolti quando vuoi sentirti bene?" },

  { cat: "profondo", text: "Cosa ti fa sentire davvero ascoltato quando parli?" },
  { cat: "profondo", text: "Qual è una cosa che hai imparato su te stesso solo di recente?" },
  { cat: "profondo", text: "Cosa significa per te \"fidarsi\" di qualcuno fino in fondo?" },
  { cat: "profondo", text: "Qual è il pensiero che ti torna in mente nei momenti di silenzio?" },

  { cat: "divertente", text: "Racconta il momento più assurdo di un primo appuntamento, reale o immaginario." },
  { cat: "divertente", text: "Se dovessi scegliere un film per descrivere la tua settimana, quale sarebbe?" },
  { cat: "divertente", text: "Qual è la scusa più creativa che hai usato per arrivare in ritardo?" },
  { cat: "divertente", text: "Inventa un nome buffo per il gruppo di stasera." },

  { cat: "ricordi", text: "Qual è il primo ricordo che hai di una vera risata condivisa con qualcuno qui presente?" },
  { cat: "ricordi", text: "Racconta un momento in cui qualcuno ti ha fatto una sorpresa che non dimenticherai mai." },
  { cat: "ricordi", text: "Qual è la canzone legata a un ricordo importante della tua vita?" },
  { cat: "ricordi", text: "Descrivi il posto che, se potessi, rivisiteresti domani stesso." },

  { cat: "sfida", text: "Fai indovinare un film mimandolo: chi lo indovina guadagna un punto." },
  { cat: "sfida", text: "Proponi una gara veloce a tua scelta: chi vince guadagna un punto." },
  { cat: "sfida", text: "Racconta una barzelletta: se qualcuno ride, guadagni un punto." },
  { cat: "sfida", text: "Sfida un'altra persona a battere il tuo record in una prova a scelta: chi vince guadagna un punto." },

  { cat: "intimita", text: "Guardatevi negli occhi per trenta secondi senza parlare, poi condividete cosa avete provato." },
  { cat: "intimita", text: "Raccontami un momento in cui ti sei sentito amato o amata da me senza che dicessi nulla." },
  { cat: "intimita", text: "Qual è un piccolo gesto che faccio e che per te significa più di quanto immagini?" },
  { cat: "intimita", text: "Prendimi per mano e raccontami a cosa pensavi quando ci siamo incontrati la prima volta." },
  { cat: "intimita", text: "Cosa vorresti che io sapessi di te oggi, in questo momento della nostra vita?" },
  { cat: "intimita", text: "Descrivi un ricordo di noi due che porti sempre con te nei giorni difficili." },
  { cat: "intimita", text: "Qual è una cosa che ammiri di me e che non ti dico mai abbastanza spesso?" },
  { cat: "intimita", text: "Se potessimo rivivere un giorno insieme, quale sceglieresti e perché?" },
  { cat: "intimita", text: "Raccontami una paura che hai riguardo al nostro futuro, senza timore di dirla." },
  { cat: "intimita", text: "Qual è il modo in cui preferisci essere consolato o consolata da me?" },
  { cat: "intimita", text: "Abbracciatevi per un minuto intero, poi raccontate cosa avete sentito." },
  { cat: "intimita", text: "Cosa ti fa sentire desiderato o desiderata da me?" },
  { cat: "intimita", text: "Qual è un sogno che vorresti costruire insieme a me nei prossimi anni?" },
  { cat: "intimita", text: "Raccontami un tuo pensiero ricorrente su di noi che non hai mai detto ad alta voce." },
  { cat: "intimita", text: "Di' tre parole che descrivono cosa provi per me in questo momento." },
  { cat: "intimita", text: "Qual è il momento in cui hai capito che con me potevi essere davvero te stesso o te stessa?" },
  { cat: "intimita", text: "Accarezzami una mano mentre mi racconti cosa apprezzi della nostra quotidianità insieme." },
  { cat: "intimita", text: "Cosa vorresti che non cambiasse mai tra noi, qualsiasi cosa succeda?" },
  { cat: "intimita", text: "Raccontami come immagini noi due tra dieci anni." },
  { cat: "intimita", text: "Qual è una cosa che ti fa venire voglia di restare, anche nei giorni più difficili?" },
  { cat: "rompighiaccio", text: "Qual è la prima app che apri appena sveglio o sveglia?" },
  { cat: "rompighiaccio", text: "Se potessi avere una skill istantanea, quale sceglieresti?" },
  { cat: "rompighiaccio", text: "Qual è il tuo comfort food preferito nelle giornate no?" },
  { cat: "rompighiaccio", text: "Che città vorresti visitare almeno una volta nella vita?" },
  { cat: "rompighiaccio", text: "Qual è l'ultima cosa nuova che hai provato e ti è piaciuta?" },
  { cat: "rompighiaccio", text: "Preferisci mare o montagna, e perché?" },
  { cat: "rompighiaccio", text: "Qual è il tuo modo preferito di rilassarti dopo una giornata pesante?" },
  { cat: "rompighiaccio", text: "Che serie TV consiglieresti a occhi chiusi?" },
  { cat: "rompighiaccio", text: "Qual è l'oggetto più utile che tieni sempre in borsa o in tasca?" },
  { cat: "rompighiaccio", text: "Se potessi cenare con una persona famosa, viva o del passato, chi sceglieresti?" },
  { cat: "rompighiaccio", text: "Qual è il tuo ricordo di vacanza preferito degli ultimi anni?" },
  { cat: "rompighiaccio", text: "Che hobby vorresti iniziare se avessi più tempo?" },
  { cat: "rompighiaccio", text: "Qual è la parola della tua lingua che preferisci di più?" },
  { cat: "rompighiaccio", text: "Preferisci organizzare tutto in anticipo o improvvisare?" },

  { cat: "profondo", text: "Cosa ti aiuta davvero a calmarti quando sei in ansia?" },
  { cat: "profondo", text: "Qual è la cosa più coraggiosa che hai fatto negli ultimi anni?" },
  { cat: "profondo", text: "Cosa significa per te \"avere successo\" nella vita?" },
  { cat: "profondo", text: "Qual è un consiglio che hai ricevuto e che porti sempre con te?" },
  { cat: "profondo", text: "Cosa ti fa perdere la pazienza più facilmente?" },
  { cat: "profondo", text: "Qual è la parte di te che stai ancora imparando ad accettare?" },
  { cat: "profondo", text: "Cosa ti dà davvero un senso di scopo nella vita quotidiana?" },
  { cat: "profondo", text: "Qual è la differenza tra la persona che eri cinque anni fa e quella di oggi?" },
  { cat: "profondo", text: "Cosa vorresti dire al te stesso di dieci anni fa?" },
  { cat: "profondo", text: "Qual è un limite che hai imparato a porre e di cui vai fiero?" },
  { cat: "profondo", text: "Cosa ti fa sentire in pace con te stesso?" },
  { cat: "profondo", text: "Qual è la cosa che ammiri di più nelle persone che ti circondano?" },
  { cat: "profondo", text: "Cosa significa per te perdonare qualcuno davvero?" },
  { cat: "profondo", text: "Qual è il pensiero che ti motiva nei momenti di stanchezza?" },

  { cat: "divertente", text: "Descrivi il tuo peggior taglio di capelli di sempre." },
  { cat: "divertente", text: "Se dovessi avere un jingle personale, come suonerebbe?" },
  { cat: "divertente", text: "Qual è la app che usi in modo più imbarazzante di quanto ammetteresti?" },
  { cat: "divertente", text: "Racconta la volta in cui hai confuso completamente due persone." },
  { cat: "divertente", text: "Se fossi un piatto del menu di un ristorante, quale saresti?" },
  { cat: "divertente", text: "Qual è la frase che dici troppo spesso senza accorgertene?" },
  { cat: "divertente", text: "Inventa una scusa assurda per uscire da una situazione noiosa." },
  { cat: "divertente", text: "Racconta il regalo più inutile che tu abbia mai ricevuto." },
  { cat: "divertente", text: "Se dovessi vincere un premio per qualcosa della tua vita quotidiana, per cosa sarebbe?" },
  { cat: "divertente", text: "Qual è la teoria del complotto più divertente che conosci?" },
  { cat: "divertente", text: "Descrivi il tuo outfit ideale per una \"giornata storta\"." },
  { cat: "divertente", text: "Racconta la figuraccia più memorabile fatta davanti a sconosciuti." },
  { cat: "divertente", text: "Se dovessi cambiare nome per un giorno, quale sceglieresti?" },
  { cat: "divertente", text: "Qual è il suono più fastidioso che esista secondo te?" },

  { cat: "ricordi", text: "Qual è il primo concerto o evento dal vivo che ricordi?" },
  { cat: "ricordi", text: "Racconta un insegnante o mentore che ha lasciato un segno in te." },
  { cat: "ricordi", text: "Qual è il gioco a cui giocavi di più da bambino?" },
  { cat: "ricordi", text: "Descrivi la stanza della tua infanzia con più dettagli possibili." },
  { cat: "ricordi", text: "Qual è il primo lavoro o piccola responsabilità che hai avuto?" },
  { cat: "ricordi", text: "Racconta un Natale o una festa che ricordi con particolare affetto." },
  { cat: "ricordi", text: "Qual è la prima volta che ti sei sentito davvero indipendente?" },
  { cat: "ricordi", text: "Descrivi un'estate che ricordi come speciale." },
  { cat: "ricordi", text: "Qual è l'oggetto di famiglia a cui sei più legato e perché?" },
  { cat: "ricordi", text: "Racconta un viaggio in auto o in treno che ricordi ancora bene." },
  { cat: "ricordi", text: "Qual è la ricetta di famiglia che ti riporta a casa?" },
  { cat: "ricordi", text: "Descrivi il primo animale domestico che hai avuto o desiderato." },
  { cat: "ricordi", text: "Qual è il ricordo più vivido legato alla scuola?" },
  { cat: "ricordi", text: "Racconta un momento in cui qualcuno ha creduto in te più di quanto credessi tu stesso." },

  { cat: "intimita", text: "Raccontami cosa ti fa sentire al sicuro quando sei con me." },
  { cat: "intimita", text: "Qual è un modo silenzioso in cui ti mostro affetto che noti sempre?" },
  { cat: "intimita", text: "Descrivi cosa provi quando ci addormentiamo vicini." },
  { cat: "intimita", text: "Raccontami una cosa che vorresti che facessimo più spesso insieme." },
  { cat: "intimita", text: "Qual è il complimento che vorresti sentirti dire più spesso da me?" },
  { cat: "intimita", text: "Cosa ti fa ridere di me che nessun altro nota?" },
  { cat: "intimita", text: "Raccontami come ti senti quando ci riappacifichiamo dopo una discussione." },
  { cat: "intimita", text: "Qual è un momento normale, non speciale, in cui ti sei sentito profondamente felice con me?" },
  { cat: "intimita", text: "Cosa vorresti che io capissi di te senza doverlo spiegare a parole?" },
  { cat: "intimita", text: "Raccontami cosa significa per te scegliere ogni giorno di stare insieme." },

  { cat: "sfida", text: "Fai ridere qualcuno del gruppo entro 10 secondi, senza toccarlo." },
  { cat: "sfida", text: "Racconta la bugia più assurda che riesci a inventare sul momento, poi rivela che è falsa." },
  { cat: "sfida", text: "Scambia il tono di voce con la persona alla tua sinistra per il turno successivo." },
  { cat: "sfida", text: "Proponi un gioco di parole a catena: chi si blocca fa una piccola penitenza." },
  { cat: "sfida", text: "Fai indovinare una parola usando solo sinonimi, senza mai dirla." },
  { cat: "sfida", text: "Canta le prime due righe di una canzone a scelta di qualcun altro." },
  { cat: "sfida", text: "Fai un discorso di 20 secondi come se stessi ricevendo un premio immaginario." },
  { cat: "sfida", text: "Descrivi una persona del gruppo usando solo aggettivi positivi che iniziano con la stessa lettera del suo nome." },
  { cat: "sfida", text: "Proponi una sfida di equilibrio: chi resta più a lungo su un piede vince un punto." },
  { cat: "sfida", text: "Racconta una storia di due frasi che finisce con un colpo di scena." },
  { cat: "sfida", text: "Fai indovinare un'emozione mimandola senza usare le mani." },
  { cat: "sfida", text: "Scambia un complimento con la persona di fronte a te, guardandola negli occhi." },
  { cat: "sfida", text: "Proponi una gara di memoria: ripeti in ordine gli oggetti nominati dal gruppo, uno alla volta." },
  { cat: "sfida", text: "Racconta il tuo miglior consiglio di vita in una sola frase." },
  { cat: "sfida", text: "Fai indovinare un mestiere mimandolo, senza parlare." },
  { cat: "sfida", text: "Proponi un brindisi a tema a sorpresa scelto da un altro giocatore." },
  { cat: "sfida", text: "Racconta una parola inventata e la sua definizione, convincendo gli altri che esiste davvero." },
  { cat: "sfida", text: "Fai una gara di sguardo fisso con qualcuno: chi ride o distoglie lo sguardo perde un punto." },
  { cat: "sfida", text: "Descrivi il gruppo di stasera come se fosse una squadra sportiva e inventa un nome." },
  { cat: "sfida", text: "Racconta la barzelletta più vecchia che conosci." },
  { cat: "sfida", text: "Fai indovinare un film usando solo tre parole indizio." },
  { cat: "sfida", text: "Proponi una piccola gara di velocità: chi trova più parole che iniziano con una lettera data in 15 secondi vince un punto." },
  { cat: "sfida", text: "Racconta un evento della giornata come se fosse un titolo di giornale scandalistico." },
  { cat: "sfida", text: "Fai un applauso teatrale a qualcuno per un motivo a tua scelta." },
  { cat: "sfida", text: "Proponi uno scambio di ruoli per la prossima domanda: rispondi tu al posto di un altro giocatore." },
  { cat: "sfida", text: "Racconta una previsione assurda su come sarà la prossima settimana di qualcuno del gruppo." },
  { cat: "sfida", text: "Fai indovinare un animale imitandone il verso." },
  { cat: "sfida", text: "Proponi una sfida di rima: crea due versi che facciano rima su un tema dato dal gruppo." },
  { cat: "sfida", text: "Racconta la cosa più strana che hai in tasca o in borsa in questo momento." },
  { cat: "sfida", text: "Fai un elogio sincero a te stesso per trenta secondi, senza fermarti." },
  { cat: "sfida", text: "Proponi una sfida al buio: chiudi gli occhi e descrivi la stanza a memoria." },
  { cat: "sfida", text: "Racconta cosa faresti con un'ora di tempo libero extra oggi, in dettaglio." },
  { cat: "sfida", text: "Fai indovinare un oggetto della stanza descrivendolo senza nominarlo." },
  { cat: "sfida", text: "Proponi una sfida di improvvisazione: inventa un breve dialogo tra due personaggi a scelta del gruppo." },
  { cat: "quiz", text: "Qual è il pianeta più grande del sistema solare?", options: ["Giove", "Saturno", "Nettuno"], correct: 0 },
  { cat: "quiz", text: "Quanti continenti ci sono sulla Terra?", options: ["5", "6", "7"], correct: 2 },
  { cat: "quiz", text: "Qual è il fiume più lungo del mondo?", options: ["Nilo", "Rio delle Amazzoni", "Mississippi"], correct: 0 },
  { cat: "quiz", text: "Qual è la capitale dell'Australia?", options: ["Sydney", "Melbourne", "Canberra"], correct: 2 },
  { cat: "quiz", text: "In che anno è caduto il Muro di Berlino?", options: ["1987", "1989", "1991"], correct: 1 },
  { cat: "quiz", text: "Qual è l'elemento chimico con simbolo \"Au\"?", options: ["Argento", "Oro", "Alluminio"], correct: 1 },
  { cat: "quiz", text: "Quanti anni dura un secolo?", options: ["10", "100", "1000"], correct: 1 },
  { cat: "quiz", text: "Qual è l'oceano più grande del mondo?", options: ["Atlantico", "Indiano", "Pacifico"], correct: 2 },
  { cat: "quiz", text: "Chi ha dipinto la Gioconda?", options: ["Leonardo da Vinci", "Michelangelo", "Raffaello"], correct: 0 },
  { cat: "quiz", text: "Qual è la lingua più parlata al mondo come madrelingua?", options: ["Inglese", "Mandarino", "Spagnolo"], correct: 1 },
  { cat: "quiz", text: "Quante corde ha una chitarra classica?", options: ["4", "6", "8"], correct: 1 },
  { cat: "quiz", text: "Qual è il paese più popoloso del mondo?", options: ["Cina", "India", "Stati Uniti"], correct: 1 },
  { cat: "quiz", text: "Qual è l'osso più lungo del corpo umano?", options: ["Femore", "Tibia", "Omero"], correct: 0 },
  { cat: "quiz", text: "Quanti minuti ci sono in un giorno?", options: ["1200", "1440", "1600"], correct: 1 },
  { cat: "quiz", text: "Qual è il metallo liquido a temperatura ambiente?", options: ["Mercurio", "Piombo", "Stagno"], correct: 0 },
  { cat: "quiz", text: "In quale continente si trova l'Egitto?", options: ["Asia", "Africa", "Europa"], correct: 1 },
  { cat: "quiz", text: "Qual è lo sport nazionale del Giappone?", options: ["Judo", "Sumo", "Karate"], correct: 1 },
  { cat: "quiz", text: "Quanti pianeti ci sono nel sistema solare?", options: ["7", "8", "9"], correct: 1 },
  { cat: "quiz", text: "Qual è la moneta ufficiale del Giappone?", options: ["Yuan", "Won", "Yen"], correct: 2 },
  { cat: "quiz", text: "Chi ha scritto \"Romeo e Giulietta\"?", options: ["Shakespeare", "Dante", "Molière"], correct: 0 },
  { cat: "quiz", text: "Qual è il mammifero più grande del mondo?", options: ["Elefante africano", "Balenottera azzurra", "Giraffa"], correct: 1 },
  { cat: "quiz", text: "Quanti lati ha un esagono?", options: ["5", "6", "7"], correct: 1 },
  { cat: "quiz", text: "Qual è la montagna più alta del mondo?", options: ["K2", "Everest", "Kilimangiaro"], correct: 1 },
  { cat: "quiz", text: "In quale sport si gioca il \"Roland Garros\"?", options: ["Tennis", "Golf", "Rugby"], correct: 0 },
  { cat: "quiz", text: "Qual è il colore ottenuto mescolando blu e giallo?", options: ["Viola", "Verde", "Arancione"], correct: 1 },
  { cat: "quiz", text: "Quanti giocatori ci sono in una squadra di calcio in campo?", options: ["9", "11", "13"], correct: 1 },
  { cat: "quiz", text: "Qual è la capitale della Francia?", options: ["Lione", "Marsiglia", "Parigi"], correct: 2 },
  { cat: "quiz", text: "Qual è il gas più abbondante nell'atmosfera terrestre?", options: ["Ossigeno", "Azoto", "Anidride carbonica"], correct: 1 },
  { cat: "quiz", text: "In quale anno è iniziata la Prima Guerra Mondiale?", options: ["1912", "1914", "1916"], correct: 1 },
  { cat: "quiz", text: "Qual è l'animale simbolo della Cina?", options: ["Tigre", "Panda", "Drago"], correct: 1 },
  { cat: "quiz", text: "Quante ossa ha circa il corpo umano adulto?", options: ["106", "206", "306"], correct: 1 },
  { cat: "quiz", text: "Qual è il deserto più grande del mondo?", options: ["Sahara", "Gobi", "Antartico"], correct: 2 },
  { cat: "quiz", text: "Qual è la valuta ufficiale del Regno Unito?", options: ["Euro", "Sterlina", "Dollaro"], correct: 1 },
  { cat: "quiz", text: "Quanti minuti dura il tempo regolamentare di una partita di calcio?", options: ["60", "90", "120"], correct: 1 },
  { cat: "quiz", text: "Qual è il pianeta più vicino al Sole?", options: ["Venere", "Mercurio", "Marte"], correct: 1 },
  { cat: "quiz", text: "Chi ha formulato la teoria della relatività?", options: ["Isaac Newton", "Albert Einstein", "Galileo Galilei"], correct: 1 },
  { cat: "quiz", text: "Qual è la città più popolosa d'Italia?", options: ["Milano", "Roma", "Napoli"], correct: 1 },
  { cat: "quiz", text: "In quale paese si trova la Torre Eiffel?", options: ["Italia", "Francia", "Spagna"], correct: 1 },
  { cat: "quiz", text: "Qual è l'organo più grande del corpo umano?", options: ["Fegato", "Pelle", "Cervello"], correct: 1 },
  { cat: "quiz", text: "Quanti minuti ci sono in un'ora?", options: ["50", "60", "70"], correct: 1 },
  { cat: "quiz", text: "Qual è la lingua ufficiale del Brasile?", options: ["Spagnolo", "Portoghese", "Italiano"], correct: 1 },
  { cat: "quiz", text: "Qual è il simbolo chimico dell'acqua?", options: ["H2O", "CO2", "O2"], correct: 0 },
  { cat: "quiz", text: "Quanti anelli olimpici ci sono nel logo dei Giochi Olimpici?", options: ["4", "5", "6"], correct: 1 },
  { cat: "quiz", text: "Qual è la capitale del Canada?", options: ["Toronto", "Vancouver", "Ottawa"], correct: 2 },
  { cat: "quiz", text: "Qual è l'insetto che produce il miele?", options: ["Formica", "Ape", "Vespa"], correct: 1 },
  { cat: "quiz", text: "Quante zampe ha un ragno?", options: ["6", "8", "10"], correct: 1 },
  { cat: "quiz", text: "Qual è la stagione più fredda dell'anno nell'emisfero nord?", options: ["Estate", "Inverno", "Autunno"], correct: 1 },
  { cat: "quiz", text: "Quale colore rappresenta tradizionalmente la pace su una bandiera?", options: ["Bianco", "Nero", "Rosso"], correct: 0 },
  { cat: "quiz", text: "Qual è il pianeta noto come \"pianeta rosso\"?", options: ["Marte", "Venere", "Giove"], correct: 0 },
  { cat: "quiz", text: "Qual è l'unità di misura della temperatura più usata in Europa?", options: ["Fahrenheit", "Celsius", "Kelvin"], correct: 1 },
  { cat: "sfida", jolly: true, groupOnly: true, bonus: 3, text: "JOLLY! Il gruppo sceglie una sfida a sorpresa per te: se la vinci guadagni 3 punti invece di 1." },
  { cat: "sfida", jolly: true, groupOnly: true, bonus: 2, text: "JOLLY! Sfida a testa o croce un avversario a tua scelta: chi vince guadagna 2 punti." },
  { cat: "sfida", jolly: true, groupOnly: true, bonus: 3, text: "JOLLY! Rispondi correttamente a una domanda lampo posta dal gruppo e guadagni 3 punti." },
  { cat: "sfida", jolly: true, groupOnly: true, bonus: 4, text: "JOLLY! Fai indovinare una parola a mimo: se il gruppo la indovina entro 15 secondi guadagni 4 punti." },
  { cat: "sfida", jolly: true, groupOnly: true, bonus: 2, text: "JOLLY! Scegli tu chi affronta la prossima sfida: se vince quella persona, guadagni comunque 2 punti anche tu." },
].map((c, i) => ({ ...c, id: i }));
